- name: Create base application directory
  become: yes
  become_user: root
  file: dest=/opt/mongochem mode=755 owner=mongochemdev group=mongochemdev state=directory
  tags:
    - base

- name: Add PPA key for nodejs
  become: yes
  become_user: root
  command: "apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 68576280"
  tags:
    - base

- name: Add PPA for nodejs
  become: yes
  become_user: root
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_4.x {{ ansible_distribution_release }} main"
  tags:
    - base

- name: Update package manager
  become: yes
  become_user: root
  apt: update_cache=yes
  tags:
    - base

- name: Install nodejs
  become: yes
  become_user: root
  apt:
    name: nodejs
  tags:
    - base

- name: Update npm
  become: yes
  become_user: root
  command: "npm install -g npm@3"

- name: Install base packages
  become: yes
  become_user: root
  apt: name={{ item }} state=present
  with_items:
    - git
    - python3-dev
    - python3-pip
    - python-virtualenv
  tags:
    - base
    - girder
