- name: Create base application directory
  sudo: yes
  file: dest=/opt/mongochem mode=755 owner=mongochemdev group=mongochemdev state=directory
  tags:
    - base

- name: Add nodejs PPA
  apt_repository: repo='ppa:chris-lea/node.js' update_cache=no
  sudo: yes
  tags: girder

- name: Update package manager
  apt: update_cache=yes
  sudo: yes
  tags:
    - base

- name: Install base packages
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
    - git
    - python3-dev
    - python3-pip
    - nodejs
  tags:
    - base
    - girder
