version: '2'
services:
  mongo:
    image: mongo:latest
    volumes:
     - mongo:/data/db
  nginx-dev:
    image: openchemistry/nginx:dev
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - 8888:80
    depends_on:
      - 'girder'
      - 'hub'
  ansible:
    image: openchemistry/ansible
    build:
      context: ansible
      dockerfile: Dockerfile
    depends_on:
      - 'girder'
    volumes:
     - ../../ansible:/ansible

volumes:
    mongo:


