version: "2.0"
services:
  girder:
    volumes:
      - $OPENCHEMISTRYPY:/openchemistrypy
  celery_command:
    volumes:
      - $OPENCHEMISTRYPY:/openchemistrypy
  celery_monitor:
    volumes:
      - $OPENCHEMISTRYPY:/openchemistrypy

