version: '2'
services:
  mongo:
    image: mongo:4.2.3

    volumes:
     - mongo:/data/db
    ports:
     # We expose this port on the host to allow dump/restor of data from the host.
     - 127.0.0.1:27020:27017
  nginx-dev:
    image: openchemistry/nginx:dev
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
     - 127.0.0.1:8888:8888
    depends_on:
      - 'girder'
      - 'hub'
      - 'client'


  client:
    image: openchemistry/mongochemclient

  ansible:
    image: openchemistry/ansible
    build:
      context: .
      dockerfile: ansible/Dockerfile
    depends_on:
      - 'girder'
    volumes:
     - ../../ansible:/ansible

  gridengine:
    privileged: true
    image: openchemistry/gridengine
    build:
      context: gridengine
      dockerfile: Dockerfile
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      - job_data:/data

volumes:
  mongo:
  job_data:


