version: "2.0"
services:
  girder:
    volumes:
      - $CUMULUS/girder/cumulus:/girder/plugins/cumulus
      - $CUMULUS/girder/taskflow:/girder/plugins/taskflow
      - $CUMULUS/girder/sftp:/girder/plugins/sftp
      - $CUMULUS/girder/newt:/girder/plugins/newt

