version: "2.0"
services:
  girder:
    volumes:
      - $MONGOCHEMSERVER/girder/app:/mongochemserver/girder/app
      - $MONGOCHEMSERVER/girder/notebooks:/mongochemserver/girder/notebooks
      - $MONGOCHEMSERVER/girder/molecules:/mongochemserver/girder/molecules
      - $MONGOCHEMSERVER/girder/queues:/mongochemserver/girder/queues
