- name: Check for existing dataset
  uri:
    url: "{{ jena_url }}/$/datasets/{{ jena_dataset }}"
    user: "{{ jena_admin_user }}"
    password: "{{ jena_admin_password }}"
    method: GET
    status_code:
      - 200
      - 404
  register: get_dataset

- name: Create Jena dataset
  uri:
    url: "{{ jena_url }}/$/datasets"
    user: "{{ jena_admin_user }}"
    password: "{{ jena_admin_password }}"
    method: POST
    body_format: form-urlencoded
    body:
    - [ dbName, "{{ jena_dataset }}"  ]
    - [ dbType, tdb ]
  when: get_dataset.status == 404