- name: Install java ( needed for 3DMol build! )
  become: yes
  become_user: root
  apt: name={{ item }} state=present
  with_items:
    - default-jre

- name: Clone client from GitHub
  git: repo=https://github.com/openchemistry/mongochemclient.git version={{mongochemclient_version|default('master')}} dest=/opt/mongochem/client

- name: Run npm install for client
  npm: path=/opt/mongochem/client

- name: Build the client HTML5 code
  command: npm run build chdir=/opt/mongochem/client
