- name: Create mongochemdev user
  user: name=mongochemdev shell=/bin/bash
  tags: users
  sudo: yes

- name: Give mongochemdev user passwordless sudo
  lineinfile: "dest=/etc/sudoers state=present regexp='^mongochemdev' line='mongochemdev ALL=(ALL) NOPASSWD: ALL'"
  tags: users
  sudo: yes

- name: Add authorized keys for mongochemdev
  sudo: yes
  authorized_key: user=mongochemdev
                  key="{{ lookup('file', item)}}"
  with_fileglob:
    - "{{ keys_directory }}/public_keys/*"
  tags: users
