- name: restart girder
  girder:
    host: "{{girder_host}}"
    port: "{{girder_port}}"
    scheme: "{{girder_scheme}}"
    apiRoot: "{{girder_api_root}}"
    username: "mongochem"
    password: "{{ mongochem_password }}"
    put:
      path: "system/restart"
  listen:
    - restart girder
