- name: Create Girder monogchem user
  girder:
    apiUrl: "{{ansible_girder_api_url}}"
    user:
      firstName: "mongochem"
      lastName: "mongochem"
      login: "mongochem"
      password: "{{ mongochem_password }}"
      email: "mongochem@kitware.com"
      admin: yes
    state: present

- name: Create Girder cumulus user
  girder:
    apiUrl: "{{ansible_girder_api_url}}"
    username: "mongochem"
    password: "{{ mongochem_password }}"
    user:
      firstName: "cumulus"
      lastName: "cumulus"
      login: "cumulus"
      password: "{{ cumulus_password }}"
      email: "cumulus@kitware.com"
      admin: yes
    state: present

- name: Create Girder cumulus group
  girder:
    apiUrl: "{{ansible_girder_api_url}}"
    username: "mongochem"
    password: "{{ mongochem_password }}"
    group:
      name: "cumulus"
      description: "The cumulus group"
      users:
        - login: cumulus
          type: member

- name: Create filesystem assetstore
  girder:
    apiUrl: "{{ansible_girder_api_url}}"
    username: "mongochem"
    password: "{{ mongochem_password }}"
    assetstore:
      name: "Filesystem Assetstore"
      type: "filesystem"
      root: "/assetstore"
      current: true
    state: present

- name: Configure app configuration
  girder:
    apiUrl: "{{ansible_girder_api_url}}"
    username: "mongochem"
    password: "{{ mongochem_password }}"
    setting:
      key: "{{item.key}}"
      value: "{{item.value}}"
    state: present
  with_items:
    - {
      "key": "app.features.notebooks",
      "value": "{{ app_feature_notebooks | default(true) }}"
    }
    - {
      "key": "app.deployment.site",
      "value": "{{ app_deployment_site | default('') }}"
    }

- name: Enable CORS requests
  girder:
    apiUrl: "{{ansible_girder_api_url}}"
    username: "mongochem"
    password: "{{ mongochem_password }}"
    setting:
      key: "{{item.key}}"
      value: "{{item.value}}"
    state: present
  with_items:
    - {
      "key": "core.cors.allow_origin",
      "value": "*"
    }
    - {
      "key": "core.cors.allow_methods",
      "value": "GET"
    }
  when: enable_cors is defined

- include: newt-auth.yml
  when: nersc is defined

- include: oauth-auth.yml
  when: oauth_google_client_id is defined

- include: dev.yml
  when: dev is defined
