- name: Create Girder monogchem user
  girder:
    host: "{{girder_host}}"
    port: "{{girder_port}}"
    scheme: "{{girder_scheme}}"
    apiRoot: "{{girder_api_root}}"
    user:
      firstName: "mongochem"
      lastName: "mongochem"
      login: "mongochem"
      password: "{{ mongochem_password }}"
      email: "mongochem@kitware.com"
      admin: yes
    state: present

- name: Create Girder cumulus user
  girder:
    host: "{{girder_host}}"
    port: "{{girder_port}}"
    scheme: "{{girder_scheme}}"
    apiRoot: "{{girder_api_root}}"
    username: "mongochem"
    password: "{{ mongochem_password }}"
    user:
      firstName: "cumulus"
      lastName: "cumulus"
      login: "cumulus"
      password: "{{ cumulus_password }}"
      email: "cumulus@kitware.com"
      admin: yes
    state: present

- name: Create Girder cumulus group
  girder:
    host: "{{girder_host}}"
    port: "{{girder_port}}"
    scheme: "{{girder_scheme}}"
    apiRoot: "{{girder_api_root}}"
    username: "mongochem"
    password: "{{ mongochem_password }}"
    group:
      name: "cumulus"
      description: "The cumulus group"
      users:
        - login: cumulus
          type: member

- name: Enable cumulus plugins
  girder:
    host: "{{girder_host}}"
    port: "{{girder_port}}"
    scheme: "{{girder_scheme}}"
    apiRoot: "{{girder_api_root}}"
    username: "mongochem"
    password: "{{ mongochem_password }}"
    plugins:
      - cumulus
      - sftp
      - newt
      - taskflow
    state: present

- name: Enable Queues plugin
  girder:
    host: "{{girder_host}}"
    port: "{{girder_port}}"
    scheme: "{{girder_scheme}}"
    apiRoot: "{{girder_api_root}}"
    username: "mongochem"
    password: "{{ mongochem_password }}"
    plugins:
      - queues
    state: present

- name: Enable OC plugin
  girder:
    host: "{{girder_host}}"
    port: "{{girder_port}}"
    scheme: "{{girder_scheme}}"
    apiRoot: "{{girder_api_root}}"
    username: "mongochem"
    password: "{{ mongochem_password }}"
    plugins:
      - molecules
    state: present

- name: Enable notebooks plugin
  girder:
    host: "{{girder_host}}"
    port: "{{girder_port}}"
    scheme: "{{girder_scheme}}"
    apiRoot: "{{girder_api_root}}"
    username: "mongochem"
    password: "{{ mongochem_password }}"
    plugins:
      - notebooks
    state: present

- name: Enable app plugin
  girder:
    host: "{{girder_host}}"
    port: "{{girder_port}}"
    scheme: "{{girder_scheme}}"
    apiRoot: "{{girder_api_root}}"
    username: "mongochem"
    password: "{{ mongochem_password }}"
    plugins:
      - app
    state: present

- name: restart girder
  girder:
    host: "{{girder_host}}"
    port: "{{girder_port}}"
    scheme: "{{girder_scheme}}"
    apiRoot: "{{girder_api_root}}"
    username: "mongochem"
    password: "{{ mongochem_password }}"
    put:
      path: "system/restart"

- name: Wait until server restarts
  wait_for:
    host="{{girder_host}}"
    port="{{girder_port}}"
    delay=5

- name: Create filesystem assetstore
  girder:
    host: "{{girder_host}}"
    port: "{{girder_port}}"
    scheme: "{{girder_scheme}}"
    apiRoot: "{{girder_api_root}}"
    username: "mongochem"
    password: "{{ mongochem_password }}"
    assetstore:
      name: "Filesystem Assetstore"
      type: "filesystem"
      root: "/assetstore"
      current: true
    state: present

- name: Configure app configuration
  girder:
    host: "{{girder_host}}"
    port: "{{girder_port}}"
    scheme: "{{girder_scheme}}"
    username: "mongochem"
    password: "{{ mongochem_password }}"
    setting:
      key: "{{item.key}}"
      value: "{{item.value}}"
    state: present
  with_items:
    - {
      "key": "app.features.notebooks",
      "value": "{{ app_feature_notesbooks | default(true) }}"
    }

- include: newt-auth.yml
  when: nersc is defined

- include: oauth-auth.yml
  when: oauth_google_client_id is defined

- include: dev.yml
  when: dev is defined
