- name: Enable NEWT plugin
  girder:
    host: "{{girder_host}}"
    port: "{{girder_port}}"
    scheme: "{{girder_scheme}}"
    apiRoot: "{{girder_api_root}}"
    username: "mongochem"
    password: "{{ mongochem_password }}"
    plugins:
      - newt
    state: present

- name: restart girder
  girder:
    host: "{{girder_host}}"
    port: "{{girder_port}}"
    scheme: "{{girder_scheme}}"
    apiRoot: "{{girder_api_root}}"
    username: "mongochem"
    password: "{{ mongochem_password }}"
    put:
      path: "system/restart"

- name: Wait until server restarts
  wait_for:
    host="{{girder_host}}"
    port="{{girder_port}}"
    delay=5

- name: Close registration
  girder:
    host: "{{girder_host}}"
    port: "{{girder_port}}"
    scheme: "{{girder_scheme}}"
    apiRoot: "{{girder_api_root}}"
    username: "mongochem"
    password: "{{ mongochem_password }}"
    setting:
      key: "{{item.key}}"
      value: "{{item.value}}"
    state: present
  with_items:
    - {
      "key": "core.registration_policy",
      "value": "closed"
    }

- name: Allow NEWT users to login even though registration is closed
  girder:
    host: "{{girder_host}}"
    port: "{{girder_port}}"
    scheme: "{{girder_scheme}}"
    apiRoot: "{{girder_api_root}}"
    username: "mongochem"
    password: "{{ mongochem_password }}"
    setting:
      key: "{{item.key}}"
      value: "{{item.value}}"
    state: present
  with_items:
    - {
      "key": "newt.ignore_registration_policy",
      "value": true
    }

- name: restart girder
  girder:
    host: "{{girder_host}}"
    port: "{{girder_port}}"
    scheme: "{{girder_scheme}}"
    apiRoot: "{{girder_api_root}}"
    username: "mongochem"
    password: "{{ mongochem_password }}"
    put:
      path: "system/restart"

- name: Wait until server restarts
  wait_for:
    host="{{girder_host}}"
    port="{{girder_port}}"
    delay=5

