- name: Close registration
  girder:
    apiUrl: "{{ansible_girder_api_url}}"
    username: "mongochem"
    password: "{{ mongochem_password }}"
    setting:
      key: "{{item.key}}"
      value: "{{item.value}}"
    state: present
  with_items:
    - {
      "key": "core.registration_policy",
      "value": "closed"
    }

- name: Allow NEWT users to login even though registration is closed
  girder:
    apiUrl: "{{ansible_girder_api_url}}"
    username: "mongochem"
    password: "{{ mongochem_password }}"
    setting:
      key: "{{item.key}}"
      value: "{{item.value}}"
    state: present
  with_items:
    - {
      "key": "newt.ignore_registration_policy",
      "value": true
    }
