- name: Configure OAuth plugins
  girder:
    apiUrl: "{{ansible_girder_api_url}}"
    username: "mongochem"
    password: "{{ mongochem_password }}"
    setting:
      key: "{{item.key}}"
      value: "{{item.value}}"
    state: present
  with_items:
    - {
      "key": "oauth.google_client_id",
      "value": "{{ oauth_google_client_id }}"
    }
    - {
      "key": "oauth.google_client_secret",
      "value": "{{ oauth_google_client_secret }}"
    }
    - {
      "key": "oauth.providers_enabled",
      "value": ["google"]
    }
