- name: Enable OAuth plugins
  girder:
    host: "{{girder_host}}"
    port: "{{girder_port}}"
    scheme: "{{girder_scheme}}"
    username: "mongochem"
    password: "{{ mongochem_password }}"
    plugins:
      - oauth
  state: present
  notify: restart girder

- name: restart girder
  girder:
    host: "{{girder_host}}"
    port: "{{girder_port}}"
    scheme: "{{girder_scheme}}"
    apiRoot: "{{girder_api_root}}"
    username: "mongochem"
    password: "{{ mongochem_password }}"
    put:
      path: "system/restart"

- name: Wait until server restarts
  wait_for:
    host="{{girder_host}}"
    port="{{girder_port}}"
    delay=5

- name: Configure OAuth plugins
  girder:
    host: "{{girder_host}}"
    port: "{{girder_port}}"
    scheme: "{{girder_scheme}}"
    username: "mongochem"
    password: "{{ mongochem_password }}"
    setting:
      key: "{{item.key}}"
      value: "{{item.value}}"
    state: present
  with_items:
    - {
      "key": "oauth.google_client_id",
      "value": "{{ oauth_google_client_id }}"
    }
    - {
      "key": "oauth.google_client_secret",
      "value": "{{ oauth_google_client_secret }}"
    }
    - {
      "key": "oauth.providers_enabled",
      "value": ["google"]
    }
  notify: restart girder

- name: Wait until server restarts
  wait_for:
    host="{{girder_host}}"
    port="{{girder_port}}"
    delay=5

