FROM jupyterhub/singleuser

USER root

RUN apt-get update && apt-get -y install git

RUN /opt/conda/bin/pip install jupyterhub==0.7.2

RUN  /opt/conda/bin/pip install git+https://github.com/girder/girder_jupyterhub.git@master

RUN  /opt/conda/bin/pip install git+https://github.com/girder/girder_jupyter.git@master

USER jovyan
