FROM jupyterhub/jupyterhub:0.7.2

# Install dockerspawner, postgres
RUN /opt/conda/bin/conda install psycopg2=2.7 && \
    /opt/conda/bin/conda clean -tipsy && \
    /opt/conda/bin/pip install \
    dockerspawner==0.8.*

RUN  /opt/conda/bin/pip install git+https://github.com/girder/girder_jupyterhub.git@master

COPY jupyterhub_config.py  /srv/jupyterhub/jupyterhub_config.py

#COPY login.html /opt/conda/share/jupyter/hub/templates
