- name: Configure Avogadro settings
  girder:
    apiUrl: "{{ansible_girder_api_url}}"
    username: "mongochem"
    password: "{{ mongochem_password }}"
    setting:
      key: "{{item.key}}"
      value: "{{item.value}}"
    state: present
  with_items:
    - {
      "key": "molecules.avogadro.url",
      "value": "{{ avogadro_url | default('http://avogadro:5001') }}"
    }
