version: '2'
services:
  web-nginx:
    image: openchemistry/certbot:oc
    labels:
      io.rancher.container.pull_image: always
    build:
      dockerfile: Dockerfile
    cap_drop:
    - ALL
    cap_add:
    - CHOWN
    - DAC_OVERRIDE
    - SETUID
    - SETGID
    - NET_BIND_SERVICE
    volumes:
    - web-certbot-webroot.oc:/usr/share/nginx/html
    group_add:
    - nginx
volumes:
  web-certbot-webroot.oc:
    external: true
    driver: rancher-nfs
