version: '2'
services:
  girder:
    build:
      context: . 
      dockerfile: girder/Dockerfile
    command: -d ${MONGODB_URL}

  nginx:
      build:
       context: nginx
       dockerfile: Dockerfile
      ports:
          - 8080:80
      depends_on:
        - 'girder'

  rabbitmq:
      image: rabbitmq

  celery-command:
    build:
      context: .
      dockerfile: celery/Dockerfile
    command: celery worker --app=cumulus -b ${RABBITMQ_URL} -n command --config=cumulus.celery.commandconfig --loglevel=INFO
    depends_on:
      - 'rabbitmq'

  celery-monitor:
    build:
      context: .
      dockerfile: celery/Dockerfile
    command: celery worker --app=cumulus -b ${RABBITMQ_URL} -n monitor -Q monitor --config=cumulus.celery.monitorconfig --loglevel=INFO
    depends_on:
      - 'rabbitmq'


