version: '2'
services:
  girder:
    network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile.girder
    command: -d ${MONGODB_URL}

  nginx:
      build:
       context: .
       dockerfile: Dockerfile.nginx
      ports:
          - 8080:80
      depends_on:
        - 'girder'

  rabbitmq:
      image: rabbitmq

  celery-command:
    build:
      context: .
      dockerfile: Dockerfile.celery
    command: celery worker --app=cumulus -b ${RABBITMQ_URL} -n command --config=cumulus.celery.commandconfig --loglevel=INFO
    depends_on:
      - 'rabbitmq'

  celery-monitor:
    build:
      context: .
      dockerfile: Dockerfile.celery
    command: celery worker --app=cumulus -b ${RABBITMQ_URL} -n monitor -Q monitor --config=cumulus.celery.monitorconfig --loglevel=INFO
    depends_on:
      - 'rabbitmq'


