- name: Configure Open Babel settings
  girder:
    host: "{{girder_host}}"
    port: "{{girder_port}}"
    scheme: "{{girder_scheme}}"
    username: "mongochem"
    password: "{{ mongochem_password }}"
    setting:
      key: "{{item.key}}"
      value: "{{item.value}}"
    state: present
  with_items:
    - {
      "key": "molecules.openbabel.url",
      "value": "{{ openbabel_url | default('http://openbabel:5000') }}"
    }
