- name: Copy over site configuration ( SSL )
  template: src="../files/mongochem-ssl.j2" dest=/etc/nginx/sites-available/mongochem mode=611 owner=root
  notify:
    - restart nginx
  when: ssl

- name: Copy over site configuration
  template: src="../files/mongochem.j2" dest=/etc/nginx/sites-available/mongochem mode=611 owner=root
  notify:
    - restart nginx
  when: not ssl


- name: Disable default configuration
  file: dest=/etc/nginx/sites-enabled/default state=absent
  notify:
    - restart nginx

- name: Enable mongochem configuration
  file: src=/etc/nginx/sites-available/mongochem dest=/etc/nginx/sites-enabled/mongochem state=link
  tags: nginx
  notify:
    - restart nginx
