- name: Create users
  hosts: all
  user: ubuntu
  roles:
    - users

- name: Create/install base system
  hosts: all
  user: mongochemdev
  roles:
    - base

- name: Install and configure MongoChem components
  hosts: girder
  user: mongochemdev
  roles:
    - mongochem

- name: Install and configure Girder
  hosts: girder
  user: mongochemdev
  roles:
    - girder


- name: Install and configure nginx
  hosts: mongochem
  user: mongochemdev
  roles:
    - nginx