- hosts: all
  gather_facts: no
  tasks:
  - name: Install python
    raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3)
    become: yes
    become_user: root
  - name: Update packages
    apt:
      only_upgrade: yes
      update_cache: yes
    become: yes
    become_user: root
  - name: Install pip
    apt:
      name: python3-pip
    become: yes
    become_user: root
  roles:
    - role: users
      become: yes
      become_user: root

- hosts: docker-compose
  vars:
    - docker_users:
        - mongochemdev
  roles:
    - role: geerlingguy.docker
      become: yes
      become_user: root
  tasks:
  - name: Install docker_compose
    pip:
      name:
        - docker-compose
        - docker
        - PyYAML
    become: yes
    become_user: root

- hosts: certbot
  roles:
    - role: certbot
  become: yes
  become_user: mongochemdev

- hosts: docker-compose
  roles:
    - role: docker_compose
  become: yes
  become_user: mongochemdev

- hosts: docker-compose
  tasks:
  - name: Install girder_client
    pip:
      name:
        - girder_client
    become: yes
    become_user: root

- hosts: docker-compose
  roles:
    - role: girder

- hosts: docker-compose
  roles:
    - role: jena

- hosts: docker-compose
  roles:
    - role: openbabel

- hosts: docker-compose
  roles:
    - role: avogadro

