- name: Create users
  hosts: all
  user: ubuntu
  roles:
    - users

- name: Create/install base system
  hosts: all
  user: mongochemdev
  roles:
    - base

- name: Compile/install avogadrolibs
  hosts: girder
  user: mongochemdev
  roles:
    - avogadrolibs

- name: Install Open Babel
  hosts: girder
  user: mongochemdev
  roles:
    - openbabel

- name: Install and configure MongoChem components
  hosts: girder
  user: mongochemdev
  roles:
    - mongochem

- name: Setup Mongo
  become: yes
  become_user: root
  hosts: girder
  roles:
    - role: mongodb

- name: Install Girder
  become: yes
  become_user: mongochemdev
  hosts: girder
  roles:
  - role: girder
    girder_path: /opt/mongochem/girder

  post_tasks:
    - name: Symlink molecules Girder plugin
      file:
        src: /opt/mongochem/server/girder/molecules
        dest: /opt/mongochem/girder/plugins/molecules
        state: link
      tags:
        - girder
        - girder_setup

    - name: Restart the Girder server
      girder:
        username: "{{mongochem_admin_user}}"
        password: "{{mongochem_admin_password }}"
        put:
          path: "system/restart"
      tags:
        - girder
        - girder_setup

    - name: Wait for Girder to restart
      wait_for: port=8080 delay=5
      tags:
        - girder
        - girder_setup

    - name: Install girder_client (needed by ansible module)
      become: yes
      become_user: root
      pip:
        name: file:///opt/mongochem/girder/clients/python
      tags:
        - girder
        - girder_setup

    - name: Create Girder mongochem user
      girder:
        user:
          firstName: "mongochem"
          lastName: "admin"
          login: "{{mongochem_admin_user}}"
          password: "{{mongochem_admin_password}}"
          email: "{{mongochem_admin_email}}"
          admin: yes
        state: present
      tags:
        - girder
        - girder_setup

    - name: Enable Girder plugins
      girder:
        username: "{{mongochem_admin_user}}"
        password: "{{mongochem_admin_password }}"
        plugins:
          - "{{item}}"
        state: present
      with_items: "{{girder_plugins}}"
      tags:
        - girder
        - girder_setup

    - name: Restart the Girder server
      girder:
        username: "{{mongochem_admin_user}}"
        password: "{{mongochem_admin_password }}"
        put:
          path: "system/restart"
      tags:
        - girder
        - girder_setup

    - name: Wait for Girder to restart
      wait_for: port=8080 delay=5
      tags:
        - girder
        - girder_setup

    - name: Configure OAuth plugin
      girder:
        username: "{{mongochem_admin_user}}"
        password: "{{mongochem_admin_password }}"
        setting:
          key: "{{item.key}}"
          value: "{{item.value}}"
        state: present
      with_items:
        - {
            key: "oauth.google_client_id",
            value: "{{oauth_google_client_id}}"
          }
        - {
            key: "oauth.google_client_secret",
            value: "{{oauth_google_client_secret}}"
          }
      tags:
        - girder
        - girder_setup

    - name: Create directory for asset store
      become: yes
      become_user: root
      file: dest={{file_system_asset_store_root}} mode=755 owner=mongochemdev group=mongochemdev state=directory
      tags:
        - girder
        - girder_setup

    - name: Create filesystem assetstore
      girder:
        username: "{{mongochem_admin_user}}"
        password: "{{mongochem_admin_password }}"
        assetstore:
          name: "{{file_system_asset_store_name}}"
          type: "filesystem"
          root: "{{file_system_asset_store_root}}"
          current: true
        state: present
      tags:
        - girder
        - girder_setup

    # Add some sample data
    - name: Download sample data to remote host
      get_url:
        url: https://data.kitware.com/api/v1/file/58ed16868d777f16d095fd73/download
        dest: /tmp/dump.tar.gz
        checksum: sha512:2664dd609a7a3452cb3b7d7fd47d59e9e82ef4f4810285a677bf22a3e01ba0c993a73c16f8095394dacb8c3ae71ad5934d6d95af042f2b11a3a740ab576b3016
      tags:
        - girder
        - girder_setup

    - name: Extract sample data
      command: tar zxvf /tmp/dump.tar.gz
      args:
        chdir: /tmp
        creates: /tmp/dump
      tags:
        - girder
        - girder_setup

    - name: Add sample molecules to database
      shell: "mongorestore -d girder /tmp/dump/girder/"
      tags:
        - girder
        - girder_setup

    - name: Cleanup sample data from remote host
      file: path={{item}} state=absent
      with_items:
        - /tmp/dump
        - /tmp/dump.tar.gz
      tags:
        - girder
        - girder_setup

  handlers:
    - include: handlers/girder.yml

- name: Install and configure nginx
  hosts: mongochem
  user: mongochemdev
  roles:
    - nginx

