- name: Template girder configuration
  template:
    src: jena.env.j2
    dest: "{{ mongochemdeploy }}/docker/jena/jena.env"
    owner: mongochemdev
    group: mongochemdev

- name: Change ownership to mongochemdev
  file:
    path: "{{ mongochemdeploy }}/docker/jena/jena.env"
    owner: mongochemdev
    group: mongochemdev
  become: yes
  become_user: root

- name: Bring up Jena stack
  docker_service:
    project_src: "{{ mongochemdeploy }}/docker/jena/"
    pull: yes
    state: present
